tests/unit/deprecation-collector-test.js, vendor/ember-cli-deprecation-workflow/main.js
Make it much prettier :D
```javascript
window.deprecationWorkflow = window.deprecationWorkflow || {};
window.deprecationWorkflow.config = {
workflow: [
{ matchMessage: \"First deprecation\", handler: \"silence\" },
{ matchMessage: \"Second deprecation\", handler: \"silence\" }
]
};
```
Addresses #1
=> Fix formatting of flushDeprecations.

tests/unit/deprecation-collector-test.js, vendor/ember-cli-deprecation-workflow/main.js
Having the `handler` first, makes it much easier to scan the file and
tweak individual settings.
=> Reorder workflow property order in flushDeprecations.

tests/unit/deprecation-collector-test.js, vendor/ember-cli-deprecation-workflow/main.js
When set to truthy value, an error is thrown if the deprecation was not matched by one of the existing workflows.
This is very useful to ensure that no new deprecations are introduced that are not already known.
=> Add throwOnUnhandled config flag.

tests/unit/deprecation-collector-test.js, vendor/ember-cli-deprecation-workflow/main.js
The deprecationCollector **must** be first to ensure that even handled (or those that are thrown due to the `throwOnUnhandled` flag) are collected properly.
=> Ensure all deprecations are logged.

index.js
This ensures that as soon as the deprecation manager is loaded, we can begin handling deprecations (previously we waited until the app bundle was loaded and received more deprecations from vendor).
=> Ensure `deprecationManager.config` is present as early as possible.

.travis.yml, ember-cli-build.js, index.js
This still allows deprecation handlers to be present in production builds when ran with the `ember test` command since users may be relying on the deprecation manager to be present when running their test suites against a production database.
Fixes #16.
=> Only include helpers while running with tests.

tests/acceptance/workflow-config-test.js, tests/dummy/config/deprecation-workflow.js, tests/unit/deprecation-collector-test.js, vendor/ember-cli-deprecation-workflow/main.js
Can now match deprecations based on the `id` passed in the options
to `deprecate`.
Fixes #3.
=> Add support for `idMatch`

README.md, generate-deprecations-tree.js, index.js, package.json
This will be removed from ember-cli-template-lint once this lands and is released...
=> Include template deprecations processing.

index.js
Hi,
This should fix the deprecation
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-deprecation-workflow`
```
which is now displayed when running `ember` commands using ember-cli > 2.6
Thanks
=> CoreObject 1.x and 2.x Compat

README.md
These two sections in the `readme` would have been very useful to me, hopefully others find it useful. It was not obvious to me production builds would not `log` or `throw` until I looked through the source code.  While looking at the source code, I found tests for `throwOnUnhandled` which I found extremely useful. I work on a large team, and not everyone is deeply experienced in Ember. There is nothing preventing warnings from finding their way into the logs.  Someone on the team referenced an old stack overflow answer which introduced a deprecation. Now that we have zero deprecation warnings, we want to keep it that way by forcing tests to fail.
=> document production builds and catch-all

generate-deprecations-tree.js, index.js, package.json, yarn.lock
Silences the `.read` / `.rebuild` API deprecation.
Fixes https://github.com/mixonic/ember-cli-deprecation-workflow/issues/52
=> Update broccoli node to be broccoli-plugin based.

.travis.yml, config/ember-try.js
Adding these versions back to ember-try config for now, we may still decide to drop ember@1.13 support but I wanted to maintain support for now.
=> Add Ember 1.13, 2.4, 2.8, and 2.12 back into config/ember-try.js.

README.md, index.js, package.json
Some application setups may use alternative `config` directories.
To customize, in app's `ember-cli-build`, add an entry under `options` for this addon:
```js
const options = {
'ember-cli-deprecation-workflow': {
configDir: '/my-config'
}
}
```
=> Allow custom addon config directory

index.js
If `ember-cli-deprecation-workflow` is not in top-level dependency `this.app` will throw following error,
```
TypeError: Cannot read property 'tests' of undefined
at Class._shouldInclude (/Users/snrai/Projects/test-addon/node_modules/ember-cli-deprecation-workflow/index.js:19:21)
```
This fix will check if there is an `app` in `this` if not then fetch the `app` using `this._findHost` function.
=> this.app is not always present

tests/acceptance/workflow-config-test.js, tests/unit/deprecation-collector-test.js
Addresses failing tests for the release/beta/canary channels of Ember.
=> Address a deprecated import path for deprecate in tests

tests/acceptance/workflow-config-test.js, vendor/ember-cli-deprecation-workflow/main.js
Limits console log to avoid causing ember server to hang which can happen if there is too much logging.
=> Limit logging

index.js, package.json, yarn.lock
This dependency is only required for Ember versions through 2.1, however
on master support for pre-2.12 has been dropped.
Fixes #113
=> Drop debug handler polyfill

vendor/ember-cli-deprecation-workflow/main.js
Generally use modern JS style, no more var.
Extracted from https://github.com/mixonic/ember-cli-deprecation-workflow/pull/118
=> Update main.js code style

tests/acceptance/workflow-config-test.js, tests/unit/deprecation-collector-test.js
Fixes per [RFC #649](https://github.com/emberjs/rfcs/pull/649)
=> Fix deprecation-without-for and deprecation-without-since deprecation warnings

tests/index.html
Remove extraneous qunit-fixture until ember-qunit gets major version bump
These elements were introduced in #92 as part of ember-qunit upgrade but ember-qunit was reverted in #110 which made interface QUnit interface unusable (technically extra div covers everything on screen).
=> Fix qunit interface

tests/acceptance/workflow-config-test.js, tests/dummy/config/deprecation-workflow.js, vendor/ember-cli-deprecation-workflow/main.js
The prior implementation was checking `count` without incrementing it, and the implementation which wanted to log the limit message on the 100th message was logging it on the 101st. Additionally, the check for presence of the option.id was not correct.
Extracted from https://github.com/mixonic/ember-cli-deprecation-workflow/pull/118
=> [BUGFIX] Check the incremented count for limit

tests/acceptance/workflow-config-test.js, tests/dummy/config/deprecation-workflow.js, tests/unit/deprecation-collector-test.js
Remove a test for "modern" arguments which are now just used through the whole codebase. Cause the test suite to throw when an unhandled exception is encountered.
Remove all use RAISE_ON_DEPRECATION stuff, as this addon has its own configuration for throwing on unhandled deprecation which should be under test here.
Extracted from https://github.com/mixonic/ember-cli-deprecation-workflow/pull/118
=> Clean up test config for clarity

config/ember-try.js, yarn.lock
ember-jquery 2.0.0 includes all patches needed to support a green CI. Update to it.
Also re-roll yarn.
=> Update ember-try to use ember-jquery release

README.md
=> Remove beta label for 2.x

README.md, index.js
This allows the addon to be enabled / disabled through configuration in `ember-cli-build.js`:
```js
'ember-cli-deprecation-workflow': {
enabled: true,
},
```
Useful when your app doesn't include test files in the development environment.
Based on @GavinJoyce's [fork](https://github.com/intercom/ember-cli-deprecation-workflow/pull/1).
=> Config option for enabling/disabling the add-on.

package.json
This addon doesn't use htmlbars directly (only for tests), so no need for it to be in direct dependencies.
All tests passed locally
=> Move ember-cli-htmlbars to devDeps

index.js, package-lock.json, package.json, vendor/ember-cli-deprecation-workflow/deprecation-workflow.js
#159 first removed all the broccoli usage, then brought it back, I believe to bring back https://github.com/mixonic/ember-cli-deprecation-workflow/blob/master/vendor/ember-cli-deprecation-workflow/main.js. But actually the custom broccoli magic does not seem needed anymore, especially no need to bring in the `config/deprecation-workflow.js` file into the vendor tree anymore.
=> Remove unused broccoli magic

README.md
It looks like these were missed in #159.
There‘s another in [this comment](https://github.com/mixonic/ember-cli-deprecation-workflow/blob/0b4cbe79b3d450722f1053f145176fbf736fd764/vendor/ember-cli-deprecation-workflow/deprecation-workflow.js), I could add that if it should be changed too?
=> Update configuration paths in documentation

package.json
this fixes the release process and updates the link in npm
the automatic github releases fails without this change: https://github.com/ember-cli/ember-cli-deprecation-workflow/actions/runs/9889225039/job/27314811230
=> fix repository link in package.json

package.json, pnpm-lock.yaml
Supersedes: https://github.com/ember-cli/ember-cli-deprecation-workflow/pull/194
=> Remove @ember/string (it's unused)

addon/index.js, tests/unit/handle-deprecation-workflow-test.js
The `matchMessage` config already supports passing a Regex, this is adding the same capability for `matchId`.
=> Support RegExp for matchId

README.md, addon/index.js, tests/acceptance/flush-deprecations-test.js, tests/acceptance/workflow-config-test.js, tests/unit/deprecation-collector-test.js, tests/unit/flush-deprecations-test.js
Running `flushDeprecations()` will always emit a config where all detected deprecations are silenced. But that is not always what you want. E.g. when you want your config to have `throwOnUnhandled` enabled, you might want to have all known deprecations to be listed (so they don't throw), but with a `log` handler.
This is now possible by running `flushDeprecations({ handler: 'log' })` instead. The default remains `silence`, so this is a non-breaking change.
-- 
Edit: 
Internally, this is removing support for deprecations that don't have an ID. Having an ID is asserted for since this [PR](https://github.com/emberjs/ember.js/pull/16934), which landed way before the earliest version of 3.28 which we support here.
This simplifies the internal collector logic, to just add IDs to a `Set` and …
=> Allow passing a custom handler to flushDeprecations

index.d.ts
Upon updating to the latest I was pleasantly surprised to find types included, but couldn't use them because they incorrectly claim the options are all mandatory.
=> Options are optional

addon/index.js
When using throw to catch deprecations it's really nice to have the ID along with the message.
=> Throw Deprecation ID
